git:
  parseEmoji: true

gui:
  showIcons: true

os:
  editPreset: "nvim"

customCommands:
  - key: "<c-e>"
    context: "files"
    description: "commit files with format"
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "Fix bugs or issues"
            value: "fix"
          - name: "feat"
            description: "Add new features"
            value: "feat"
          - name: "docs"
            description: "Update or improve documentation"
            value: "docs"
          - name: "style"
            description: "Fix code formatting, UI-only changes"
            value: "style"
          - name: "refactor"
            description: "Code improvements without performance enhancements"
            value: "refactor"
          - name: "test"
            description: "Add or improve tests"
            value: "test"
          - name: "perf"
            description: "Performance improvements"
            value: "perf"
          - name: "chore"
            description: "Changes or improvements to the build process"
            value: "chore"
          - name: "wip"
            description: "Work in progress"
            value: "wip"
      - type: "input"
        title: "(Optional) Enter the scope"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "menu"
        title: "Choose the emoji"
        key: "Emoji"
        options:
          - name: "(empty)"
            description: ""
            value: ""
          - name: ":ambulance:"
            description: "(fix) ğŸš‘ Critical bug fix"
            value: ":ambulance:"
          - name: ":bug:"
            description: "(fix) ğŸ› Bug fix"
            value: ":bug:"
          - name: ":+1:"
            description: "(fix) ğŸ‘ Feature improvement or modification"
            value: ":+1:"
          - name: ":cop:"
            description: "(fix) ğŸ‘® Security-related fix"
            value: ":cop:"
          - name: ":tada:"
            description: "(feat) ğŸ‰ Major feature addition"
            value: ":tada:"
          - name: ":sparkles:"
            description: "(feat) âœ¨ Partial feature addition"
            value: ":sparkles:"
          - name: ":up:"
            description: "(feat) ğŸ†™ Update dependencies, etc."
            value: ":up:"
          - name: ":memo:"
            description: "(docs) ğŸ“ Add or modify documentation"
            value: ":memo:"
          - name: ":bulb:"
            description: "(docs) ğŸ’¡ Add or modify comments in the source code"
            value: ":bulb:"
          - name: ":art:"
            description: "(style) ğŸ¨ Fix layout-related issues"
            value: ":art:"
          - name: ":lipstick:"
            description: "(style) ğŸ’„ Fix lint errors or code style"
            value: ":lipstick:"
          - name: ":recycle:"
            description: "(refactor) â™»ï¸ Refactoring"
            value: ":recycle:"
          - name: ":fire:"
            description: "(refactor) ğŸ”¥ Delete code or files"
            value: ":fire:"
          - name: ":green_heart:"
            description: "(test) ğŸ’š Fix tests or CI"
            value: ":green_heart:"
          - name: ":rocket:"
            description: "(perf) ğŸš€ Performance improvement"
            value: ":rocket:"
          - name: ":wrench:"
            description: "(chore) ğŸ”§ Modify configuration files"
            value: ":wrench:"
          - name: ":building_construction:"
            description: "(chore) ğŸ—ï¸ Modify architecture"
            value: ":building_construction:"
          - name: ":construction:"
            description: "(wip) ğŸš§ Work in progress"
            value: ":construction:"
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Emoji}} {{.Form.Type}}{{.Form.Scope}}: {{.Form.Message}}'. Is this okay?"
    command: 'bash -c ''type="{{.Form.Type}}"; scope="{{.Form.Scope}}"; message="{{.Form.Message}}"; emoji="{{.Form.Emoji}}"; commit_message="$emoji $type${scope:+($scope)}: $message"; git commit -m "$commit_message"'''
    loadingText: "Committing..."
